"""
data_understanding_agent.py - Reads a CSV, computes stats locally,
then calls Gemini to generate dataset_profile.md. Also builds
an initial analysis_notebook.ipynb using nbformat.
"""
import os
import io
from google import genai

from utils.file_utils import read_csv, write_markdown, ensure_output_dir
from utils.notebook_utils import (
    create_notebook, add_markdown_cell, add_code_cell, save_notebook
)


# Gemini key rotation - tries each key in order until one succeeds
_GEMINI_KEYS = [
    os.getenv("GEMINI_API_KEY20"),
    os.getenv("GEMINI_KEY1"),
    os.getenv("GEMINI_KEY2"),
    os.getenv("GEMINI_KEY3"),
]

_MODEL = "gemini-2.5-flash"


def _call_gemini(prompt: str) -> str:
    """Try each Gemini API key in round-robin until a call succeeds."""
    last_error = None
    for key in _GEMINI_KEYS:
        if not key:
            continue
        try:
            client = genai.Client(api_key=key)
            response = client.models.generate_content(
                model=_MODEL,
                contents=prompt,
            )
            return response.text
        except Exception as e:
            last_error = e
            print(f"[data_understanding_agent] Key failed, trying next... ({e})")
    raise RuntimeError(f"All Gemini API keys failed. Last error: {last_error}")


def _compute_local_stats(df) -> str:
    """Return a plain-text summary of the DataFrame for the Gemini prompt."""
    buf = io.StringIO()

    buf.write(f"Shape: {df.shape[0]} rows x {df.shape[1]} columns\n\n")

    buf.write("Column Types:\n")
    for col, dtype in df.dtypes.items():
        buf.write(f"  {col}: {dtype}\n")

    buf.write("\nMissing Values per Column:\n")
    missing = df.isnull().sum()
    for col, count in missing.items():
        pct = round(100 * count / len(df), 2)
        buf.write(f"  {col}: {count} ({pct}%)\n")

    buf.write("\nBasic Statistics (numeric columns):\n")
    buf.write(df.describe().to_string())
    buf.write("\n")

    # Value counts / unique for categorical columns
    cat_cols = df.select_dtypes(include=["object", "category"]).columns
    if len(cat_cols) > 0:
        buf.write("\nCategorical Columns - Unique Value Counts:\n")
        for col in cat_cols:
            buf.write(f"  {col}: {df[col].nunique()} unique values\n")
            top5 = df[col].value_counts().head(5)
            buf.write(f"    Top 5: {dict(top5)}\n")

    return buf.getvalue()


def _build_profile_prompt(dataset_name: str, stats_text: str) -> str:
    return f"""You are a data scientist performing Exploratory Data Analysis (EDA).

Dataset: {dataset_name}

--- COMPUTED STATISTICS ---
{stats_text}
--- END STATISTICS ---

Using the above statistics, write a comprehensive dataset_profile.md report in Markdown. Include:

1. **Dataset Overview** - what the dataset appears to contain, number of rows/columns
2. **Column Descriptions** - for each column: data type, missing %, key observations
3. **Basic Statistics Summary** - highlight min, max, mean, std for key numeric columns
4. **Missing Values Analysis** - which columns have missing data and recommended handling
5. **Categorical Variables** - top categories and their distribution
6. **Key EDA Insights** - at least 5 interesting observations or patterns from the stats
7. **Potential Data Quality Issues** - skewness, outliers, high cardinality, etc.
8. **Recommended Next Steps** - suggested analyses based on what you see

Write clearly and concisely. Use markdown headers, bullet points, and tables where helpful.
"""


def _build_notebook(df, csv_path: str, output_dir: str) -> str:
    """Build an initial Jupyter notebook with exploration cells."""
    nb = create_notebook()
    csv_filename = os.path.basename(csv_path)

    # Title 
    add_markdown_cell(nb, f"""# AStats — Initial Data Exploration

**Dataset:** `{csv_filename}`
**Generated by:** AStats Data Understanding Agent
""")

    add_code_cell(nb, """import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)
plt.style.use('seaborn-v0_8-whitegrid')
%matplotlib inline
""")

    add_markdown_cell(nb, "## 1. Load Dataset")
    add_code_cell(nb, f"""df = pd.read_csv(r"{os.path.abspath(csv_path)}")
print(f"Shape: {{df.shape}}")
df.head()
""")

    add_markdown_cell(nb, "## 2. Dataset Info & Types")
    add_code_cell(nb, """df.info()
""")
    add_code_cell(nb, """df.dtypes
""")

    add_markdown_cell(nb, "## 3. Descriptive Statistics")
    add_code_cell(nb, """df.describe(include='all')
""")

    add_markdown_cell(nb, "## 4. Missing Values")
    add_code_cell(nb, """missing = df.isnull().sum()
missing_pct = (missing / len(df) * 100).round(2)
missing_df = pd.DataFrame({'Missing Count': missing, 'Missing %': missing_pct})
missing_df[missing_df['Missing Count'] > 0].sort_values('Missing %', ascending=False)
""")
    add_code_cell(nb, """# Heatmap of missing values (if any)
if df.isnull().sum().sum() > 0:
    plt.figure(figsize=(10, 4))
    sns.heatmap(df.isnull(), cbar=False, yticklabels=False, cmap='viridis')
    plt.title('Missing Values Heatmap')
    plt.tight_layout()
    plt.show()
else:
    print("No missing values found.")
""")

    add_markdown_cell(nb, "## 5. Numeric Column Distributions")
    add_code_cell(nb, """numeric_cols = df.select_dtypes(include='number').columns.tolist()
n = len(numeric_cols)
if n > 0:
    fig, axes = plt.subplots(1, n, figsize=(5 * n, 4))
    if n == 1:
        axes = [axes]
    for ax, col in zip(axes, numeric_cols):
        df[col].dropna().hist(ax=ax, bins=30, edgecolor='white', color='steelblue')
        ax.set_title(col)
        ax.set_xlabel('')
    plt.suptitle('Numeric Column Distributions', fontsize=14)
    plt.tight_layout()
    plt.show()
""")

    add_markdown_cell(nb, "## 6. Correlation Matrix")
    add_code_cell(nb, """numeric_df = df.select_dtypes(include='number')
if numeric_df.shape[1] >= 2:
    plt.figure(figsize=(8, 6))
    corr = numeric_df.corr()
    mask = np.triu(np.ones_like(corr, dtype=bool))
    sns.heatmap(corr, mask=mask, annot=True, fmt='.2f', cmap='coolwarm',
                center=0, linewidths=0.5)
    plt.title('Correlation Matrix')
    plt.tight_layout()
    plt.show()
else:
    print("Not enough numeric columns for a correlation matrix.")
""")

    add_markdown_cell(nb, "## 7. Categorical Column Value Counts")
    add_code_cell(nb, """cat_cols = df.select_dtypes(include=['object', 'category']).columns.tolist()
for col in cat_cols:
    print(f"\\n=== {col} ===")
    print(df[col].value_counts().head(10))
""")

    path = os.path.join(output_dir, "analysis_notebook.ipynb")
    save_notebook(nb, path)
    return path


def run(csv_path: str, output_dir: str) -> str:
    """
    Run the Data Understanding Agent.

    Parameters
    ----------
    csv_path   : path to the input CSV file
    output_dir : directory where outputs will be written

    Returns
    -------
    str : absolute path to the generated dataset_profile.md
    """
    ensure_output_dir(output_dir)

    print("\n[DataUnderstandingAgent] Loading dataset...")
    df = read_csv(csv_path)
    print(f"  -> {df.shape[0]} rows x {df.shape[1]} columns")

    print("[DataUnderstandingAgent] Computing local statistics...")
    stats_text = _compute_local_stats(df)

    print("[DataUnderstandingAgent] Calling Gemini to generate dataset profile...")
    dataset_name = os.path.basename(csv_path)
    prompt = _build_profile_prompt(dataset_name, stats_text)
    profile_md = _call_gemini(prompt)

    profile_path = os.path.join(output_dir, "dataset_profile.md")
    write_markdown(profile_path, profile_md)
    print(f"[DataUnderstandingAgent] dataset_profile.md saved -> {profile_path}")

    print("[DataUnderstandingAgent] Building analysis notebook...")
    notebook_path = _build_notebook(df, csv_path, output_dir)
    print(f"[DataUnderstandingAgent] analysis_notebook.ipynb saved -> {notebook_path}")

    return profile_path
